nelmio_api_doc:
    documentation:
        info:
            title: Books store
            description: Books store api documentation
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
